### ISSUE TITLE
Oculus Quest connecting to PC but not displaying open app/game

### ISSUE THREAD

**Issue by hames754** [madmagic007/Oculus-Quest-Presence#12]
Hi I have setup according to the instructions and have confirmed "device found and running apk." I then restart the Quest and it says in discord I am playing quest but when I click on an app it does not display the app. 

If it helps I am running v16 of Oculus Quest and I'm not sure if this is currently supported.

**Comment by madmagic007** [comment]
hi, can you add me on discord so you can send images to explain exactly what you mean? link is in the Readme file at the top

**Comment by hames754** [comment]
That link does not seem to be active for me

**Comment by hames754** [comment]
I turned off windows firewall and it works

**Comment by hames754** [comment]
I then renabled the firewall and it works as well

**Comment by madmagic007** [comment]
so everything is working now?

**Comment by hames754** [comment]
yeha for future reference it required adding javaw.exe to the iwndow firewall incoming connections

**Comment by madmagic007** [comment]
weird that the firewall blocked it, I have never seen Java being blocked by firewall before.
