### ISSUE TITLE
Oculus Quest Presence displays over PC games

### ISSUE THREAD

**Issue by hames754** [madmagic007/Oculus-Quest-Presence#13]
It would be nice if Games on PC displayed over the oculus quest presence. This would allow discord to change to SteamVR apps such as Alyx when opened through virtual desktop.

**Comment by madmagic007** [comment]
the way this works, it can only detect that oculus link is active, it cant detect what game you are playing on your pc on the quest. you can however disable the presence of the quest and just have the app played on the pc show its own discord presence
