### ISSUE TITLE
I did everything a tried to troubleshoot but it doesnt work

### ISSUE THREAD

**Issue by DicciusMaximus** [madmagic007/Oculus-Quest-Presence#14]
it says the device is ready to go but when I restart my quest it doesnt work

**Comment by madmagic007** [comment]
did you follow all the troubleshooting steps on the readme page? add me on discord if the issue still persists.

**Comment by DicciusMaximus** [comment]
It still does it what's your  discord

**Comment by madmagic007** [comment]
link at the top of the readme page, click on the badge and it should open in your browser. if it doesn't take you right there, don't close the browser yet and click on it again

**Comment by RyanTheTide** [comment]
[Click here](https://discordapp.com/users/401795293797941290/) to get him on discord.
Or alternatively copy exactly from here: ⎛⎝⧹Maͫgͣiͩc⧸⎠⎞#6891
