### ISSUE TITLE
Mac OS - Status Only Stay for 1 minute, and then disappears

### ISSUE THREAD

**Issue by Bubba8291** [madmagic007/Oculus-Quest-Presence#15]
Hi, I'm on macOS. When I use this program, the status only stay for one minute and then it disappears. The program requires a restart to show up again, but it doesn't show the game I'm playing at all. I followed all of the steps correctly, so it might be a bug. This is the only thing I see when I use the program.
<img width="250" alt="Screen Shot 2020-05-26 at 2 47 22 PM" src="https://user-images.githubusercontent.com/37317442/82953677-0fdc6400-9f60-11ea-85b8-24f9c3d65489.png">

**Comment by madmagic007** [comment]
did you use the request presence to start button? this is a know issue and i hope it is fixed in the version i just released. First try using the newest version. Make sure the program is running on your pc, and then restart the quest. If you don't hit the request to start button on your pc, it shouldn't disappear. If you keep having issues, contact me  on discord (link on the readme page).

**Comment by Bubba8291** [comment]
So I got it to work, but now there is another small bug. The system will not write the config.json automatically. I had to enter my Quests IP address into the file manually. Also, the mapping.json file does not get written at all (I'm assuming it's for the games and apps), so I also had to add the content of mapping.json manually.

**Comment by madmagic007** [comment]
> So I got it to work, but now there is another small bug. The system will not write the config.json automatically. I had to enter my Quests IP address into the file manually. Also, the mapping.json file does not get written at all (I'm assuming it's for the games and apps), so I also had to add the content of mapping.json manually.

mapping.json is empty by default. You can manually put lines in it if you want to override what it gets from the lang.json found in the repository. the config.json should get automatically written to, oyu just have to set the ip via the settings window. right click the icon on the system tray and hit open settings
