### ISSUE TITLE
"Service is Not Running"

### ISSUE THREAD

**Issue by crybabymae** [madmagic007/Oculus-Quest-Presence#16]
I followed the instructions [here](https://www.youtube.com/watch?v=omhujeBPCIU), but the program only says "Service is not running" & clicking "Start Service" does not allow it to start. Recent commenters on the YouTube video are also having this problem.

**Comment by madmagic007** [comment]
have you tried hitting the terminate service button and then start again? if more people are having this it could be something to do with a software update of the quest
