### ISSUE TITLE
when I delete it then everytime my pc starts up gives me error message

### ISSUE THREAD

**Issue by DicciusMaximus** [madmagic007/Oculus-Quest-Presence#18]
It never worked for me so I deleted it. now im stuck with this dumb error message EVERY TIME i start up my pc

**Comment by madmagic007** [comment]
if you deleted all the files manually then you get that error, if you ran the Uninstaller the error shouldn't appear. go to %appdata%/microsoft/windows/start menu/startup/ and delete the oqrpc.lnk file

**Comment by GCMan777** [comment]
I found it at C:\Users\USERNAME\%AppData%\Roaming\Microsoft\Windows\Start Menu\Programs\Startup on windows 10 pro, but this was helpful in solving that issue
