### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by samward359** [madmagic007/Oculus-Quest-Presence#20]
When I install and open for the first time I get a thing to enable access to activity. That disappears immediately and I can't get back to it so the presence never shows what game I'm playing. I am on the quest 2 btw

**Comment by madmagic007** [comment]
this could be related to the quest 2, I don't have one so I can't test. 
if you have validated on the pc, try hitting the debug button and let me know what it shows. 
the acces activity should pop up every time you start it and it doesn't have the permission. you can uninstall the tool via settings and sideload it again and it will show the window again.
I will add a feature in the next update to bring up the window to grant permissions

**Comment by samward359** [comment]
Every time I uninstall and reinstall to get the permissions thing again it disappears before I can do anything. Here's the debug log 

{
    "address": "192.168.1.90",
    "delay": 3,
    "apkVersion": "2.3",
    "sleepWake": false,
    "startBoot": false,
    "notifications": true
}
Trying to request connection to quest: Found Quest and the service responded
Sending notification: Successful
Requesting game status: 
{"detailed":false,"message":"gameResponse"}

**Comment by madmagic007** [comment]
so it seems that it's an issue with the quest 2. ill look into it. if you want to, you can contact me on discord ro help with testing on the quest 2

**Comment by samward359** [comment]
That would be great. What's your discord?

**Comment by madmagic007** [comment]
link is at the top of the readme page
