### ISSUE TITLE
when the quest 2 version will be available?

### ISSUE THREAD

**Issue by avro170** [madmagic007/Oculus-Quest-Presence#24]

**Comment by RyanTheTide-old** [comment]
Hi @avrenz, unfortunately due to a significant changes Oculus implemented solely to the Oculus Quest 2’s firmware and the upgrade to Android 10 from 8 this program will not function. At its core this program relies on a permission in Android 8, in which an application in the background can report another application in the foreground’s identifier/package name. There have been many changes but this is one of them that has been broken by Oculus, this is not something @madmagic007 can fix. Thanks for your interest!

**Comment by madmagic007** [comment]
exaclty what ryan says. It could be that its just a bug in the os, it could be that the next android update on the quest 2 fixes it, so we have to wait untill then. If its the case that oculus blocks apps on quest 2, then nothing can be done at all.
Maybe there's a workaround using adb, but im unfamilear with it, i tried but failed. If there's anyone that migbt be able to help, dont hesitate and contact me!

**Comment by PauloGoncalves2002** [comment]
Any hopes if this will be available soon?

**Comment by madmagic007** [comment]
@PauloGoncalves2002 no because im still not sure what the actual issue is. Its most likely a bug on the quest 2 itself, so in that case the earliest it will be available is when that issue is resolved in a software update

**Comment by sidequestlegend** [comment]
We had a similar issue with the permission dialog being broken for something we were prototyping and the following ADB command was able to bypass and grant the permissions. Its not ideal but could allow for a workaround. 

```
adb shell "package=com.example.app; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
```

On a separate note, a user has submitted this app to SideQuest. They clearly state that they are not you and they didn't make this app so it wont get approved - this is unrelated but I said I would mention it since that is what brought me here.

**Comment by madmagic007** [comment]
@sidequestlegend can you tell me who that user is? anyways thanks for the adb command, i will test it out and make a workaround using it if possible

**Comment by madmagic007** [comment]
@sidequestlegend im unfamilear with adb and cant get the command to work. I get: `Error: Unknown operation string: PACKAGE_USAGE_STATS`

**Comment by HoomanDiscord** [comment]
I tried using ``` adb shell pm grant com.madmagic.oqrpc android.permission.PACKAGE_USAGE_STATS ``` and it runs and I can see on discord that I am playing on quest. The only part that doesn't seem to work is the beatsaber plugin but it's out of date so that may be why. I simply connected my Quest 2 to sidequest and used the "run adb" option in it to do so.

**Comment by madmagic007** [comment]
@BulletinMatches that command makes the app think that it has the permission, but it actually doesn't. that's why you can open it and it won't crash. if you look at the presence, it won't say what game you are playing because the app can't detect it because of it not actually having the permission. that's also why the beatsaber plugin doesn't work

**Comment by HoomanDiscord** [comment]
> @BulletinMatches that command makes the app think that it has the permission, but it actually doesn't. that's why you can open it and it won't crash. if you look at the presence, it won't say what game you are playing because the app can't detect it because of it not actually having the permission. that's also why the beatsaber plugin doesn't work

Ah I see I just misunderstood the issue

**Comment by HoomanDiscord** [comment]
I found something on google which could maybe work, basically on 
https://developer.android.com/guide/components/activities/background-starts 
at the very bottom it says it can start activities if it has the SYSTEM_ALERT_WINDOW permission now I can't give the app the permission as when i do it says that it has not requested it. Im not sure if this would fix your issue but it's worth a shot. the command I used was `adb shell pm grant com.madmagic.oqrpc android.permission.SYSTEM_ALERT_WINDOW` I think you just need the app to ask for that permission so the command would work.

**Comment by HoomanDiscord** [comment]
> I found something on google which could maybe work, basically on 
> https://developer.android.com/guide/components/activities/background-starts 
> at the very bottom it says it can start activities if it has the SYSTEM_ALERT_WINDOW permission now I can't give the app the permission as when i do it says that it has not requested it. Im not sure if this would fix your issue but it's worth a shot. the command I used was `adb shell pm grant com.madmagic.oqrpc android.permission.SYSTEM_ALERT_WINDOW` I think you just need the app to ask for that permission so the command would work.

There is also a foreground service permission you may need to grant if you haven't FOREGROUND_SERVICE

**Comment by madmagic007** [comment]
@BulletinMatches the activity starts from the foreground so that shouldn't be it. but I'll look into it, just incase

**Comment by HoomanDiscord** [comment]
> @BulletinMatches the activity starts from the foreground so that shouldn't be it. but I'll look into it, just incase

Here's the link to the foreground service thing https://developer.android.com/guide/components/foreground-services

**Comment by HoomanDiscord** [comment]
Also another issue and I'm not sure if this is exclusive to me but when I tried to grant it permission with the window that pops up it just closes out and I found out that settings keeps stopping so I had to grant it with adb

**Comment by madmagic007** [comment]
> Also another issue and I'm not sure if this is exclusive to me but when I tried to grant it permission with the window that pops up it just closes out and I found out that settings keeps stopping so I had to grant it with adb

that's litterally what the whole issue is. opening the window where you grant the permission causes settings to crash

**Comment by HoomanDiscord** [comment]
> > Also another issue and I'm not sure if this is exclusive to me but when I tried to grant it permission with the window that pops up it just closes out and I found out that settings keeps stopping so I had to grant it with adb
> 
> that's litterally what the whole issue is. opening the window where you grant the permission causes settings to crash

Ah well the ADB command I sent grants that perm

**Comment by HoomanDiscord** [comment]
> > > Also another issue and I'm not sure if this is exclusive to me but when I tried to grant it permission with the window that pops up it just closes out and I found out that settings keeps stopping so I had to grant it with adb
> > 
> > that's litterally what the whole issue is. opening the window where you grant the permission causes settings to crash
> 
> Ah well the ADB command I sent grants that perm 

But it still didn't show game for me I might need to do more testing in a few mins

**Comment by HoomanDiscord** [comment]
> > > > Also another issue and I'm not sure if this is exclusive to me but when I tried to grant it permission with the window that pops up it just closes out and I found out that settings keeps stopping so I had to grant it with adb
> > > 
> > > that's litterally what the whole issue is. opening the window where you grant the permission causes settings to crash
> > 
> > Ah well the ADB command I sent grants that perm 
> 
> But it still didn't show game for me I might need to do more testing in a few mins 

Running ``adb shell pm grant com.madmagic.oqrpc android.permission.PACKAGE_USAGE_STATS`` works for me because when I go into the app it shows that the permission is enabled  ![IMG20201211213907.jpg](https://user-images.githubusercontent.com/75859493/101957433-54c4a100-3bf9-11eb-866e-d0d3a8864342.jpg) I attached the pictures

**Comment by madmagic007** [comment]
like I said earlier, the command makes it think that it's granted when it's not. hence why it won't show the actual game

**Comment by HoomanDiscord** [comment]
> We had a similar issue with the permission dialog being broken for something we were prototyping and the following ADB command was able to bypass and grant the permissions. Its not ideal but could allow for a workaround. 
> 
> ```
> adb shell "package=com.example.app; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
> ```
> 
> On a separate note, a user has submitted this app to SideQuest. They clearly state that they are not you and they didn't make this app so it wont get approved - this is unrelated but I said I would mention it since that is what brought me here. 

I tried using the command replacing the example package with the actual package name just get ``'grep' is not recognized as an internal or external command, operable program or batch file.``

**Comment by madmagic007** [comment]
like I said earlier, the command makes it think that it has the perm but it hasn't. therefore it doesn't show the actual game

**Comment by HoomanDiscord** [comment]
> > We had a similar issue with the permission dialog being broken for something we were prototyping and the following ADB command was able to bypass and grant the permissions. Its not ideal but could allow for a workaround.
> > ```
> > adb shell "package=com.example.app; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
> > ```
> > 
> > 
> > On a separate note, a user has submitted this app to SideQuest. They clearly state that they are not you and they didn't make this app so it wont get approved - this is unrelated but I said I would mention it since that is what brought me here.
> 
> I tried using the command replacing the example package with the actual package name just get `'grep' is not recognized as an internal or external command, operable program or batch file.`

Ok so I got the command running by doing this
`` `adb shell
"com.madmagic.oqrpc; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo `'[0-9]+'`"``
and now it says `10089
1000
10027
10010
1000
10004
10077
10025
10058
10085
10012
10024
10084
10041
10029
10043
1000
10086
10004
10066
1000
10090
10072
1000
10076
10045
10020
10065
10061
10048
10000
1000
10082
10004
10005
1000
10070
10031
10051
10013
1000
10060
10019
1000
10054
10064
1000
2000
10033
1000
10046
10002
10079
10057
1000
10039
10023
1000
10087
10074
10062
1000
10030
10034
10052
1000
10017
1000
1000
10007
10026
10069
10063
10008
1000
10006
10021
1000
1000
10091
10078
1000
1000
10009
10018
10088
10067
10014
10036
10003
10053
10028
1000
10047
10068
10040
1073
10071
10038
10032
10055
10001
10080
10059
10081
10050
2000
1000
10015
10083
10015
1000
10073
1000
1000
10056
10044
10011
1000
1000
1000
1000
1002
10049
10015
10037
10042
10035
10075
10022
10041
10046
10040
10004
1073
10031
10056
1002
10015
1000
2000
10010: inaccessible or not found`
and still does not say what game it is

>

**Comment by HoomanDiscord** [comment]
> > > We had a similar issue with the permission dialog being broken for something we were prototyping and the following ADB command was able to bypass and grant the permissions. Its not ideal but could allow for a workaround.
> > > ```
> > > adb shell "package=com.example.app; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
> > > ```
> > > 
> > > 
> > > On a separate note, a user has submitted this app to SideQuest. They clearly state that they are not you and they didn't make this app so it wont get approved - this is unrelated but I said I would mention it since that is what brought me here.
> > 
> > 
> > I tried using the command replacing the example package with the actual package name just get `'grep' is not recognized as an internal or external command, operable program or batch file.`
> 
> Ok so I got the command running by doing this
> `` `adb shell "com.madmagic.oqrpc; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo `'[0-9]+'`" ``
> and now it says `10089 1000 10027 10010 1000 10004 10077 10025 10058 10085 10012 10024 10084 10041 10029 10043 1000 10086 10004 10066 1000 10090 10072 1000 10076 10045 10020 10065 10061 10048 10000 1000 10082 10004 10005 1000 10070 10031 10051 10013 1000 10060 10019 1000 10054 10064 1000 2000 10033 1000 10046 10002 10079 10057 1000 10039 10023 1000 10087 10074 10062 1000 10030 10034 10052 1000 10017 1000 1000 10007 10026 10069 10063 10008 1000 10006 10021 1000 1000 10091 10078 1000 1000 10009 10018 10088 10067 10014 10036 10003 10053 10028 1000 10047 10068 10040 1073 10071 10038 10032 10055 10001 10080 10059 10081 10050 2000 1000 10015 10083 10015 1000 10073 1000 1000 10056 10044 10011 1000 1000 1000 1000 1002 10049 10015 10037 10042 10035 10075 10022 10041 10046 10040 10004 1073 10031 10056 1002 10015 1000 2000 10010: inaccessible or not found`
> and still does not say what game it is
> 
> >

I ran the command by running adb shell on one line and running the actuall command on another 

adb shell
"com.madmagic.oqrpc; op=PACKAGE_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"

**Comment by KNCITTV** [comment]
Any updates on getting this working on quest 2?

**Comment by sybilleek** [comment]
Considering the fitness tracker works as a background process I don't see why it wouldn't work.  I just "think" the headers for the new android 10 TOS (basically) have to added to the xml precompile.  I have zero idea how the fitness tracker is doing it.

**Comment by sybilleek** [comment]
They're on the right track though trying to push adb shell commands at it but i think the issues lies within the xml at runtime commands.  This was coded on sdk droid 8 (which is what the original quest was Android 8.0 (API level 26) or 8.1 which was 27) There was a revision of execution done in lvl 29 sdk 10.

**Comment by sybilleek** [comment]
I've been following this thread for a month now ever since i got quest 2 and been looking at the differences.
https://developer.android.com/about/versions/10/migration

**Comment by sybilleek** [comment]
I haven't played with: (to see if any of these would be helpful)
https://developer.oculus.com/documentation/tools/book-tools/

**Comment by madmagic007** [comment]
@sybilleek background processes aren't the issue. it's that you can't grant the permission that is needed 8n order to get the current topmost process. I don't know if fitness does the same but I will look into it

**Comment by madmagic007** [comment]
big news, i got it to work. a version that supports the quest 2 is made, its just being tested now. excpect a release later this week

**Comment by jellz** [comment]
@madmagic007 Have you tested [Lauriethefish's Beat Saber Discord hook](https://github.com/Lauriethefish/Quest-Discord-Presence) with your Quest 2 fix?

**Comment by madmagic007** [comment]
@jellz I already spoke with Laurie and it will be updated to support the newest version as there is one little change with android 10. as soon as this releases, his mod will be updated!

**Comment by jellz** [comment]
Sounds great. Looking forward to the release!

**Comment by sybilleek** [comment]
Hell yeah, right on, i look forward to testing. Salud!

**Comment by madmagic007** [comment]
@sybilleek if you have quest 2 and want to help, contact me on discord

**Comment by sybilleek** [comment]
I'd love to be of any assistance as i can.  Since discord won't get off their butts and make an android app that reports status changes for android products, lol  (or runs in the background).   My point?  What this community has been doing is a worthwhile project.  Specially to people that stream.  I'm not a streamer, however I to an effect represent those that do.  One immediate request i have (and prolly will be fixed with your permissions modifications) is to allow screen shots within your app (prolly works well on OG quest but when i ran the app on quest 2 wasn't able to, and understandably so considering it was a permissions issue).  I'll find your discord and hit ya up.

**Comment by madmagic007** [comment]
Happy new year everyone. Update that supports quest 2 is released

**Comment by madmagic007** [comment]
Recent Quest 2 software update seems to have fixed the crashing issue, meaning the adb command shouldn't be neccesary anymore and setup is just like the Quest 1. The permission dialog is removed and will prompt with the permission screen like normal. if issues persist with the permission  granting, read more <a href="https://github.com/madmagic007/Oculus-Quest-Presence/wiki/Quest-2-support">here</a>
