### ISSUE TITLE
I have to request the presence to start before the presence shows

### ISSUE THREAD

**Issue by ginatails** [madmagic007/Oculus-Quest-Presence#25]
(I have quest 1, and am on Windows 10)
When I put on my quest, the discord presence doesn't work unless I open the oqrpc app and request it to start.
I reinstalled it a few weeks ago and it didn't seem to fix it.

**Comment by madmagic007** [comment]
does the presence actually work (show the current game etc), or just say you are playing the quest and nothing else?

**Comment by ginatails** [comment]
> does the presence actually work (show the current game etc), or just say you are playing the quest and nothing else?

When it works, it shows the current game. But when it doesn't work, it well, doesn't show anything.

**Comment by madmagic007** [comment]
concact me on discord so i can further assist you in resolving this

**Comment by ginatails** [comment]
> concact me on discord so i can further assist you in resolving this

Ok, I added you on discord so I can message you.
