### ISSUE TITLE
Entering ADB command for Quest 2 on Sidequest doesn't work on Mac

### ISSUE THREAD

**Issue by Maclean-D** [madmagic007/Oculus-Quest-Presence#26]
(Preface I'm on Mac)
I've installed everything and oqrpc says to view the guide for quest 2, and the guide for Quest 2 says to enter this adb command: `adb shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"  Doing so gives an error:

Error: Command failed: "/Users/millicenteisenberg/Library/Application Support/SideQuest/platform-tools/adb" -s 1WMHH814320434 shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`" /bin/sh: dumpsys: command not found Exception occurred while executing: java.lang.IllegalArgumentException: Argument expected after "--user" at android.os.ShellCommand.getNextArgRequired(ShellCommand.java:331) at com.android.server.appop.AppOpsService$Shell.parseUserPackageOp(AppOpsService.java:3283) at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:3413) at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:3203) at android.os.ShellCommand.exec(ShellCommand.java:108) at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:3373) at android.os.Binder.shellCommand(Binder.java:881) at android.os.Binder.onTransact(Binder.java:765) at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:822) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)

I know the rest of my install went correctly because it shows that I'm playing my Quest 2 when on the oqrpc screen.  I thought maybe the issue was where I installed the app on my computer so I moved the app to my user's application folder instead of the global application folder and it still didn't work.  It still shows I'm playing my quest when on the oqrpc screen either way.

**Comment by Maclean-D** [comment]
I'm running the latest version of software on my Quest 2 possible, I even have oculus move which is rolling out slowly in beta.

**Comment by HoomanDiscord** [comment]
I see, in the command you left out one bit make sure you run 

adb shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"

exactly and don't remove anything seeing as in your command there is a ` left out in "--user `dumpsys"

**Comment by HoomanDiscord** [comment]
> I see, in the command you left out one bit make sure you run 
> 
> adb shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
> 
> exactly and don't remove anything seeing as in your command there is a ` left out in "--user `dumpsys"

Or it may have been that just the ` is left out because of GitHub formatting

**Comment by HoomanDiscord** [comment]
> (Preface I'm on Mac)
> I've installed everything and oqrpc says to view the guide for quest 2, and the guide for Quest 2 says to enter this adb command: `adb shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"  Doing so gives an error:
> 
> Error: Command failed: "/Users/millicenteisenberg/Library/Application Support/SideQuest/platform-tools/adb" -s 1WMHH814320434 shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`" /bin/sh: dumpsys: command not found Exception occurred while executing: java.lang.IllegalArgumentException: Argument expected after "--user" at android.os.ShellCommand.getNextArgRequired(ShellCommand.java:331) at com.android.server.appop.AppOpsService$Shell.parseUserPackageOp(AppOpsService.java:3283) at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:3413) at com.android.server.appop.AppOpsService$Shell.onCommand(AppOpsService.java:3203) at android.os.ShellCommand.exec(ShellCommand.java:108) at com.android.server.appop.AppOpsService.onShellCommand(AppOpsService.java:3373) at android.os.Binder.shellCommand(Binder.java:881) at android.os.Binder.onTransact(Binder.java:765) at com.android.internal.app.IAppOpsService$Stub.onTransact(IAppOpsService.java:822) at android.os.Binder.execTransactInternal(Binder.java:1021) at android.os.Binder.execTransact(Binder.java:994)
> 
> I know the rest of my install went correctly because it shows that I'm playing my Quest 2 when on the oqrpc screen.  I thought maybe the issue was where I installed the app on my computer so I moved the app to my user's application folder instead of the global application folder and it still didn't work.  It still shows I'm playing my quest when on the oqrpc screen either way.

Try updating java that might help otherwise just make sure you copied the command correctly and the quest is connected correctly in side quest by looking for the green dot in the corner as the command worked for me but I use windows. Also check if your sidequest is at latest version

**Comment by Maclean-D** [comment]
> > I see, in the command you left out one bit make sure you run
> > adb shell "package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo '[0-9]+'`"
> > exactly and don't remove anything seeing as in your command there is a `left out in "--user`dumpsys"
> 
> Or it may have been that just the ` is left out because of GitHub formatting

I believe it was because the ' were left out bc of formatting.  I just copied and pasted what was on the wiki

**Comment by Maclean-D** [comment]
I just installed sidequest on my windows laptop and copy and pasted the command there and now the Quest 2 works and shows my status connected to my mac.  So I guess the issue is that the adb command only works on windows.

**Comment by Maclean-D** [comment]
(I can use it with my mac now)

**Comment by beraekoklu** [comment]
I'm also having this problem.

**Comment by beraekoklu** [comment]
And I can't connect my oculus quest 2 to my linux/windows computer because I don't have a usb-c to a converter, and wireless sidequest will not work.

**Comment by madmagic007** [comment]
@That-Mac-Daddy I will add to the wiki page that the command only works on windows. since this looks like an adb issue, it's nothing I can fix.  
@MintStudios you need to run the adb command by connecting it to to a pc else this will sadly not work.

**Comment by beraekoklu** [comment]
Will you investigate why? I don't have a usb-c to usb-a so it won't connect.

**Comment by madmagic007** [comment]
@MintStudios idk exactly what your issue is, but if it's just that you can't connect your quest to a computer, that's really nothing I can do about that.

**Comment by beraekoklu** [comment]
@madmagic007 I meant why it won't work on a mac

**Comment by Maclean-D** [comment]
The issue is that this specific adb command is not working on mac as is.  Other adb commands work so it's just a comparability issue.

**Comment by beraekoklu** [comment]
Alright, I've come up with a solution for people who have old pcs with no usb-c port or adapter.
1. You should have developer mode enabled on the quest and your account.
2. From [oculus](https://developer.oculus.com/downloads/package/oculus-go-adb-drivers/), download ADB drivers.
3. Then, on your mac, in sidequest run `adb tcpip 5555` while the quest is connected.
4. Find out the ip address of your quest from the top left corner of sidequest
4. Now, on your windows pc, install [adb](https://developer.android.com/studio/releases/platform-tools) for windows. Extract and go inside.
5. Now, find `adb.exe` and stay inside the directory. 
6. Open up the terminal, and put in `adb connect <quest-ip>:5555 (replace <quest-ip> with the ip address, and DO NOT include the arrows.)
7. Inside your quest, allow the computer to access files.

You should be done!

**Comment by beraekoklu** [comment]
@madmagic007 you could include this in the wiki page.

**Comment by madmagic007** [comment]
@MintStudios thank you, i will add it

**Comment by madmagic007** [comment]
i will link to this

**Comment by Aem1024** [comment]
well the problem is i only have a mac

**Comment by beraekoklu** [comment]
I guess virtualization might do the trick, but you'd have to add USB input to the virtual machine.

**Comment by Aem1024** [comment]
I tried using my win7 vm but i couldn't attach my quest to it

**Comment by Aem1024** [comment]
does the command work on linux though?

**Comment by beraekoklu** [comment]
Yes, it does, that's what I use

**Comment by madmagic007** [comment]
you can try installing adb drivers for Mac. oculus has drivers for the quest somewhere on their website, unsure if they have it for Mac.

**Comment by Maclean-D** [comment]
The drivers are windows only and wouldn't matter anyway.  The drivers are separate to Sidequest where you enter the adb command.  It seems to be an issue with the macOS version of Sidequest or the adb command itself.  Other commands work in sidequest it's just this one that doesn't appear too.

**Comment by Aem1024** [comment]
You can enter the command using ads in terminal though

**Comment by Aem1024** [comment]
but the drivers are sadly windows only

**Comment by madmagic007** [comment]
could try normal adb drivers for Mac if they exist. if that works then it's an issue with sidequest. if it doesn't, the' I don't know anything you csn do to fix it because the reason you even need to do this command is some issue with the os of the quest 2. if you root the device then you can run the command without need of a pc, but I do not recommend this at all

**Comment by Aem1024** [comment]
it's not an issue with side quest, i tried the command on terminal and it failed as well.

**Comment by madmagic007** [comment]
what's the location of the adb executable (idk what it's called for Mac) that was used when running it via terminal? sidequest comes with its adb drivers, so you might have used those

**Comment by Maclean-D** [comment]
Using the side quest drivers for adb obviously don't work with this command.  On windows you can get CMD adb commands by downloading android studio.  So I would assume you would get adb commands by downloading android studio on Mac.  Additionally, android studio is also available on Linux and Chromebooks.

**Comment by error7404** [comment]
The reason it "doesn't work" on mac/linux is because the `` ` `` and `$` are interpreted by the host terminal instead of adb, to fix this just type:
```bash
adb shell 'package=com.madmagic.oqrpc; op=GET_USAGE_STATS; appops set $package $op allow --user `dumpsys package $package | grep userId= | grep -Eo "[0-9]+"`'
```
(by inverting " and ' the special characters don't get interpreted by mac/linux [(ref)](https://stackoverflow.com/a/6697781/13262992))
