### ISSUE TITLE
Annoying message when i turn on my pc

### ISSUE THREAD

**Issue by Owen-3456** [madmagic007/Oculus-Quest-Presence#27]
I installed the presence stuff but it didnt work so i uninstalled it and now when i restart my pc a get a annoying message: https://imgur.com/rGyRhaT . How do i get rid of this.

ps dont tell to install the rich presence stuff

**Comment by madmagic007** [comment]
if you ran the uninstaller instead of deleting the files manually this shouldnt happen.
go to %appdata% and delete the `oculus quest discord rpc` folder. also go to %appdata%\Microsoft\Windows\Start Menu\Programs\Startup` and delete the oqrpc shortcut (.lnk)

**Comment by Owen-3456** [comment]
All good now, thanks. (I thought I did run the uninstaller but I could be wrong).
