### ISSUE TITLE
Oculus Quest 2 troubleshooting 

### ISSUE THREAD

**Issue by LightzOfTheSky** [madmagic007/Oculus-Quest-Presence#28]
Hi! I’m having some issues! I sideloaded the apk file and was able to put my IP address in and download the program. Even downloaded the new version of Java and put the special line of code in abs. However after I was still having issues. I loaded the program on my quest and no matter what I could never get it to work. I tried to uninstall and reinstall the program but it still wouldn’t work and I’m just having trouble barter trying everything and to no avail am I getting it to work. Can someone help me?? My discord is LightzOfTheSky#9402

**Comment by madmagic007** [comment]
please explain the issue you are having exaclt. othwerwise you cannot be helped

**Comment by andybak** [comment]
Because I'm a VR developer who thought I might learn something or discover something interesting.

Sorry to bother you.

**Comment by madmagic007** [comment]
closing - no response
