### ISSUE TITLE
ShellEnv status on homescreen

### ISSUE THREAD

**Issue by SammyWhamy** [madmagic007/Oculus-Quest-Presence#32]
Not sure if this is known or intended, but personally it looks weird to me.
Whenever you're on the homescreen or in some (unsupported?) apps, it just shows this:
<img width="104" alt="Screenshot 2021-03-15 025842" src="https://user-images.githubusercontent.com/45788465/111093946-6e4bf080-853a-11eb-947d-b551c05e508b.png">
It'd be nice to just change this to some default oculus logo, saying "Idling, Home Screen" for example. Or anything else along those lines

**Comment by madmagic007** [comment]
when in home it will show 
![image](https://user-images.githubusercontent.com/51405665/111810997-e584da00-88d6-11eb-97d1-1ae914f1fc8d.png)
cant reproduce your issue, i will need more information. When you get this to show, visit the ip of your quest in browser and show me what it prints

**Comment by michael-r-elp** [comment]
Can confirm getting that currently as well, it shows `"currentTop": "[Ljava.lang.String;@db23e5e" `when accessing it via a browser and that changes on every page refresh
Full Information I get is for example `{ "batteryLevel": "100%", "name": "Oculus Quest 2", "currentTop": "[Ljava.lang.String;@572697", "ownAddress": "192.168.188.30", "pcAddress": "192.168.188.20" }` in Oculus Home

**Comment by madmagic007** [comment]
Is this for quest 2 or the original quest? Still can't reproduce this issue

**Comment by michael-r-elp** [comment]
I'm on a Quest 2, so I can confirm that being a bug there on the log it says `handling com.oculus.shellenv`
