### ISSUE TITLE
Windows Defender thinks its a Virus

### ISSUE THREAD

**Issue by DiniskaWolfiii** [madmagic007/Oculus-Quest-Presence#33]
Windows Defender thinks the .zip file is a virus.
I downloaded it for a while and just reinstalled my PC during some hardware upgrades. Then I downloaded a new version and Windows Defender is telling me it has a Virus.
Attached a Screen of the message I get, but it's in german lol.

I can say to Windows Defender that its all good. Just wanted to mention.
![image](https://user-images.githubusercontent.com/54332169/111208568-3476fa80-85cb-11eb-8636-74c5be96c7ce.png)

**Comment by madmagic007** [comment]
#31, add as exception
