### ISSUE TITLE
Quest 2 warning

### ISSUE THREAD

**Issue by raynefox** [madmagic007/Oculus-Quest-Presence#35]
When i launch the application it says that you need to grant the permission using the adb ?

**Comment by madmagic007** [comment]
Then grant the permission using adb as stated in the widow.
https://github.com/madmagic007/Oculus-Quest-Presence/wiki/Quest-2-support

**Comment by raynefox** [comment]
Thanks for your response, 

That was the first thing I tried :( 

even after running the command it still appears 

![image](https://user-images.githubusercontent.com/81118135/112011683-6551b500-8b20-11eb-90fa-9d1f6336a4f9.png)

**Comment by raynefox** [comment]
I have also tried removing and reinstalling the APK and the windows client sadly nothing seems to want to fix it :(

**Comment by madmagic007** [comment]
When you run the command and it says command completed, then restart your quest and open the app. does it still give the same window notification?

**Comment by raynefox** [comment]
it does, still comes up with a window with a green bar at the top options 

Force start 
Force Stop 
Debug 
Request permissions 

then when i click request permissions it says as you are using a quest 2 you must grant permissions using adb 

sorry i would shar a screenshot but apparently i can't do that in the app

**Comment by madmagic007** [comment]
the description you gave is normal. the button that says "request permissions" is to force retry it. if you open the app normally without pressing any buttons, the window saying you need to run the adb command doesnt show, it means everything is fine

**Comment by raynefox** [comment]
Ahhh awesome not sure what happened but it looks like it is all working, thanks for your help !
