### ISSUE TITLE
Readme is missing critical info

### ISSUE THREAD

**Issue by andybak** [madmagic007/Oculus-Quest-Presence#40]
Very nice readme but at no point does it explain what the app does!

"Discord Rich Presence for the Oculus Quest" - is the closest but I've got no idea what this means in practice.

**Comment by madmagic007** [comment]
if you dont know what a discord presence is, why are you even looking at this app. name explains enough

**Comment by andybak** [comment]
Because I'm a VR developer who is curious and likes to learn new things. No need to be prickly about it - I was trying to help.
