### ISSUE TITLE
Feature request: Status should say the game your're playing not "Oculus quest"

### ISSUE THREAD

**Issue by yaukari** [madmagic007/Oculus-Quest-Presence#42]
![image](https://user-images.githubusercontent.com/75146973/120344748-de5f4c80-c2c7-11eb-8af7-f0214f384001.png)

Please do this, the entire thing is almost useless without it.
You would only have to change a few variables

**Comment by madmagic007** [comment]
discords limitations makes that impossible for me to do that for every game. beatsaber has a module that you can use that does what you want, found here
https://github.com/Lauriethefish/Quest-Discord-Presence

**Comment by yaukari** [comment]
> discords limitations makes that impossible for me to do that for every game. beatsaber has a module that you can use that does what you want, found here
> https://github.com/Lauriethefish/Quest-Discord-Presence.
> you should only need the beatsaber mod itself, not the client it also provides

Why? just force the status change to like 10 seconds and you shouldnt run into any rate limit issues.

**Comment by madmagic007** [comment]
it's not just a variable to change, it's an entire application. to have an rpc, you need to make an application, and the "oculus quest" is the name of the application. if I want it to show something else, I have to manually make and use an application for that specific game
