### ISSUE TITLE
The service detects quest 1 as quest 2

### ISSUE THREAD

**Issue by SovietBelphagor** [madmagic007/Oculus-Quest-Presence#43]
So after launching the service and trying to give it permissions it says that I have a quest 2, but I own a quest 1. So I tired to ignore it and use the adb command for quest 2 and it worked for around 30 seconds and then pc lost connection to the service. Sometimes catches it after reboot but also after around 1 min looses connection with the service

**Comment by madmagic007** [comment]
Oculus has changed the quest 1's android version to 10, which is thesame as the quest 2 and this was how i was checking if the device is the original or the 2. I am working on a workaround, but im not to osure how to detect if its a quest 1 or 2.
if anyone reading this has any idea, make sure to let me know

**Comment by madmagic007** [comment]
Found out that the desired way of doing it now works fine on the quest 2, no more adb command needed. will release updated version where it doesnt have to check for version anymore
