### ISSUE TITLE
Not starting on quest 2 startup

### ISSUE THREAD

**Issue by Caelanj** [madmagic007/Oculus-Quest-Presence#45]
Everything seems to be working fine, however when I start my quest 2 it doesn't seem to start automatically, and I have to manually open the app.

**Comment by madmagic007** [comment]
does as soon as you manually open the app, it connects and shows the presence? and is this reproducable every time?

**Comment by Caelanj** [comment]
Don't worry, it seems that it wouldn't appear as if the program was connected unless I click "Validate". My bad.
Its working fine now :)
