### ISSUE TITLE
Cannot join Pavlov: Shack servers while open.

### ISSUE THREAD

**Issue by uncreativeCultist** [madmagic007/Oculus-Quest-Presence#49]
Exactly what the title says, I can't seem to connect to Pavlov: Shack servers whenever it's open on the headset. I just seem to time out whenever attempting to join

**Comment by madmagic007** [comment]
I highly doubt this would be an issue related to my app. can you confirm this by connecting to pavlov shack server when the app is closed (press the force stop button). and confirm this is reproduceable by enabling it again?
