### ISSUE TITLE
Add: Swarm

### ISSUE THREAD

**Issue by SeeTheBridges** [madmagic007/Oculus-Quest-Presence#5]
```
"com.sketchbox.Grapple": {
		"details": "Currently playing:",
		"state": "Swarm - Closed Beta"
},
```
Wasn't sure if I should fork and do a pull request or if you'd prefer to have issues raised and tagged.

**Comment by ryanjem** [comment]
I’ll add it it my fork now and message him to add it.

**Comment by madmagic007** [comment]
added
