### ISSUE TITLE
Quest Presence isn't showing what game I'm in.

### ISSUE THREAD

**Issue by Iamuss76** [madmagic007/Oculus-Quest-Presence#50]
![image](https://user-images.githubusercontent.com/49089420/172620699-197ec1aa-1964-4ab4-ba3e-d848371056b0.png)
Even though I'm currently in a game right now, all discord is saying is this ^, i've tried multiple games, none seem to work

**Comment by Iamuss76** [comment]
![image](https://user-images.githubusercontent.com/49089420/172621088-597a7392-8de5-4bbb-a699-021a53ec5f30.png)

**Comment by madmagic007** [comment]
This looks like the application on the quest is missing the permission that is needed to get the current game. But a recent quest update broke granting that permission. i alreay have a fix but im completely rewriting the program before i release the update. 
in the meantime follow this link and it should work: https://github.com/madmagic007/Oculus-Quest-Presence/wiki/Permission-granting-issues
