### ISSUE TITLE
Mac doesnt show full sentence

### ISSUE THREAD

**Issue by kylerifqi** [madmagic007/Oculus-Quest-Presence#51]
Not sure if this is an intended feature but text on the bottom option doesnt show the bottom sentence and i cant resize the window to see it, not a big deal jsut wanted to share. Id be glad to help with testing on MacOS Catalina tho i have no Java knowledge 

![image](https://user-images.githubusercontent.com/97279512/176830003-2936fa60-c928-4ad1-8171-a3e9eb0d198d.png)

**Comment by madmagic007** [comment]
Hi, sorry for the late reply, unfortunately i dont own a mac so its quite hard to make guis that would work well, especially when it has to work on more than one platform. i dont really know how to develop guis for mac either in java
