### ISSUE TITLE
Not working anymore

### ISSUE THREAD

**Issue by c1sxr0bzn** [madmagic007/Oculus-Quest-Presence#52]
Is this project still maintained?
Won't show presence on Windows, Quest connects and has the right permissions.

**Comment by madmagic007** [comment]
hi, sorry for the late response, ive been extremely busy with other things. this seems like a typical firewall issue, try adding java (not the app itself) as an exception or temporarily disabling the firewall completely.
also i have developed a new version but was unable to test it properly, if you would like to assist in helping, please let me know or contact me on discord
