### ISSUE TITLE
Run ADB Commands Missing

### ISSUE THREAD

**Issue by DemonsOfChaos** [madmagic007/Oculus-Quest-Presence#55]
got to the part where I had to grant the app permissions from my pc. only problem is that I can't find the "Run ADB Commands" button in sidequest. it's apparently supposed to be on the top right with the other buttons, but it's just not there. tried searching up if they moved the button or something but I couldn't find anything. any ideas?

**Comment by madebylydia** [comment]
Here is the button, can you find it?
![image](https://user-images.githubusercontent.com/61093863/213933416-77fbd710-43bf-485b-9c8a-02855c10946f.png)

**Comment by DemonsOfChaos** [comment]
I could've sworn it wasn't there before thats so weird
