### ISSUE TITLE
Opening VRChat simply shows "quest" or "Oculus App Runtime" as the game.

### ISSUE THREAD

**Issue by L5-cg** [madmagic007/Oculus-Quest-Presence#59]
Anyone know how to fix this?
![image](https://github.com/madmagic007/Oculus-Quest-Presence/assets/100592537/03480421-2930-4a6a-9d54-75031f191425)

**Comment by yapgamer** [comment]
I think you have to make a module for each game, in this case VRChat

**Comment by madmagic007** [comment]
hi, sorry for the late reply. i have kind of abandoned this project as Oculus or now known as Meta seems to have broken the very thing this tool depended on. I am no longer able to detect consistently what app is currently on top.
sorry to have to disappoint you.
